[[levels]]
title = 'clone'
branch = 'master'
solution_checker = 'echo No pushing to master. Read the README file; exit 1'
flags = ['start-here']

[[levels]]
title = 'start-here'
branch = 'start-here'
solution_checker = 'hooks/checkers/start-here.sh'
flags = ['basic-1']

[[levels]]
title = 'basic-1'
branch = 'scorpion-treenware-gestatory'
solution_checker = 'hooks/checkers/basic-1.sh'
flags = ['basic-2']

[[levels]]
title = 'basic-2'
branch = 'sidespins-areae-regalio'
solution_checker = 'hooks/checkers/basic-2.sh'
flags = ['merge-1']

[[levels]]
title = 'merge-1'
branch = 'macrochiropteran-jupon-lutecium'
solution_checker = 'hooks/checkers/merge-1.sh'
flags = [
    'merge-2',
    'log-1',
]

[[levels]]
title = 'merge-2'
branch = 'poseuse-citronwood-manganese'
solution_checker = 'hooks/checkers/merge-2.sh'
flags = ['merge-3']

[[levels]]
title = 'log-1'
branch = 'turbulator-feere-reinclined'
solution_checker = 'hooks/checkers/log-1.sh'
flags = ['log-2']

[[levels]]
title = 'log-2'
branch = 'insatiably-skyjackers-program'
solution_checker = 'hooks/checkers/log-2.sh'
flags = ['log-3']

[[levels]]
title = 'log-3'
branch = 'originates-anagyrine-untolerative'
solution_checker = 'hooks/checkers/log-3.sh'
flags = ['log-4']

[[levels]]
title = 'log-4'
branch = 'belialist-interlaying-mize'
solution_checker = 'hooks/checkers/log-4.sh'
flags = ['log-5']

[[levels]]
title = 'log-5'
branch = 'pamphletary-harnessing-petticoaterie'
solution_checker = 'hooks/checkers/log-5.sh'
flags = []

[[levels]]
title = 'merge-3'
branch = 'twee-enfamish-stropharia'
solution_checker = 'hooks/checkers/merge-3.sh'
flags = ['merge-4']
