[[levels]]
title = 'clone'
branch = 'master'
solution_checker = 'echo No pushing to master. Read the README file; exit 1'
flags = ['start-here']

[[levels]]
title = 'start-here'
branch = 'start-here'
solution_checker = 'hooks/checkers/start-here.sh'
flags = ['basic-1']

[[levels]]
title = 'basic-1'
branch = 'scorpion-treenware-gestatory'
solution_checker = 'hooks/checkers/basic-1.sh'
flags = ['basic-2']

[[levels]]
title = 'basic-2'
branch = 'sidespins-areae-regalio'
solution_checker = 'hooks/checkers/basic-2.sh'
flags = ['merge-1']
