[[levels]]
	title = "clone"
	branch = "master"
	solution_checker = "echo I am on the master branch"
	flags = []  # ["start-here"], but it's implicit in the readme

[[levels]]
	title = "start-here"
	branch = "start-here"
	solution_checker = "checkers/start-here.sh"
	flags = ["merge-1"]

[[levels]]
	title = "merge-1"
	branch = "fizzling-vulture-pedial"
	solution_checker = "checkers/merge-1.sh"
	flags = ["merge-2", "log-1"]
